//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cholestabetes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InviteesMaster
    {
        public int ID { get; set; }
        public string InvitationTier { get; set; }
        public string Salutation { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public string PostalCode { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public Nullable<int> Status { get; set; }
        public string Clinic { get; set; }
        public string RegistrationCode { get; set; }
        public Nullable<System.DateTime> InvitationSentDate { get; set; }
        public string CellPhone { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> InvitedCHRC { get; set; }
        public Nullable<System.DateTime> InvitationSentDateFrench { get; set; }
        public string PaymentStatusV1 { get; set; }
        public string PaymentStatusV2 { get; set; }
        public string PaymentStatusV3 { get; set; }
    
        public virtual Province Province { get; set; }
        public virtual RegistrationStatu RegistrationStatu { get; set; }
        public virtual User User { get; set; }
    }
}
