//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cholestabetes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.PatientQuestionAnswers = new HashSet<PatientQuestionAnswer>();
            this.PatientVisits = new HashSet<PatientVisit>();
            this.VisitReminders = new HashSet<VisitReminder>();
        }
    
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Telephone { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<PatientQuestionAnswer> PatientQuestionAnswers { get; set; }
        public virtual ICollection<PatientVisit> PatientVisits { get; set; }
        public virtual ICollection<VisitReminder> VisitReminders { get; set; }
    }
}
