//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cholestabetes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientVisit
    {
        public int ID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> VisitID { get; set; }
        public Nullable<bool> Completed { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ScreenID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> PickedUpForNotification { get; set; }
    
        public virtual Visit Visit { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
