//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cholestabetes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientQuestionAnswer
    {
        public int ID { get; set; }
        public Nullable<int> QID { get; set; }
        public Nullable<int> AID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string AnswerValue { get; set; }
    
        public virtual PatientAnswer PatientAnswer { get; set; }
        public virtual PatientQuestion PatientQuestion { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
