//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cholestabetes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientQuestion
    {
        public PatientQuestion()
        {
            this.PatientAnswers = new HashSet<PatientAnswer>();
            this.PatientQuestionAnswers = new HashSet<PatientQuestionAnswer>();
        }
    
        public int ID { get; set; }
        public string QuestionText { get; set; }
        public Nullable<int> ScreenID { get; set; }
        public Nullable<int> VisitID { get; set; }
    
        public virtual Visit Visit { get; set; }
        public virtual ICollection<PatientAnswer> PatientAnswers { get; set; }
        public virtual ICollection<PatientQuestionAnswer> PatientQuestionAnswers { get; set; }
    }
}
