//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cholestabetes.Data
{
    using System;
    
    public partial class sp_GetPayeeList_Result4
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string PaymentMethod { get; set; }
        public string ChequePayableTo { get; set; }
        public string InternalRefNum { get; set; }
        public string MailingAddr1 { get; set; }
        public string MailingAddr2 { get; set; }
        public string AttentionTo { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string TaxNumber { get; set; }
        public string AdditionalInstructions { get; set; }
        public string Province { get; set; }
        public string PhysicianFirstName { get; set; }
        public string PhysicianLastName { get; set; }
    }
}
