//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cholestabetes.Data
{
    using System;
    
    public partial class sp_GetEnrollmentSummary_Result1
    {
        public Nullable<int> MOU { get; set; }
        public Nullable<int> AssesmentSurvey { get; set; }
        public Nullable<int> PayeeInformation { get; set; }
        public Nullable<int> NumPatientV1 { get; set; }
        public Nullable<int> NumPatientV2 { get; set; }
        public Nullable<int> NumPatientV3 { get; set; }
        public string PaymentStatusV1 { get; set; }
        public string PaymentStatusV2 { get; set; }
        public string PaymentStatusV3 { get; set; }
    }
}
