//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cholestabetes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.InviteesMasters = new HashSet<InviteesMaster>();
            this.Patients = new HashSet<Patient>();
            this.PayeeInfoes = new HashSet<PayeeInfo>();
            this.UserRegistrations = new HashSet<UserRegistration>();
            this.VisitReminders = new HashSet<VisitReminder>();
            this.Roles = new HashSet<Role>();
        }
    
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public bool LoginFlag { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<InviteesMaster> InviteesMasters { get; set; }
        public virtual ICollection<Patient> Patients { get; set; }
        public virtual ICollection<PayeeInfo> PayeeInfoes { get; set; }
        public virtual ICollection<UserRegistration> UserRegistrations { get; set; }
        public virtual ICollection<VisitReminder> VisitReminders { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}
